flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
  texmath:
    network-uri: true
packages:
- '..'
- '../../pandoc-citeproc'
extra-deps:
- 'aeson-0.11.1.1'
- 'texmath-0.8.5'
- 'highlighting-kate-0.6.2'
resolver: lts-5.8
