flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '..'
- location:
    git: https://github.com/jgm/pandoc-types.git
    commit: 485eb11e9869fcd4c1ca9bcd68d3ccd384230252
extra-deps:
- texmath-0.8.6.6
- pandoc-citeproc-0.10.1.1
- doctemplates-0.1.0.2
resolver: lts-7.2
