flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '..'
- location:
    git: https://github.com/jgm/pandoc-types.git
    commit: 6580565f7271eb2d15a4d71c3415316850f47b29
extra-deps:
- texmath-0.8.6.6
- pandoc-citeproc-0.10.1.2
- doctemplates-0.1.0.2
resolver: lts-7.2
