flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '..'
- location:
    git: https://github.com/jgm/pandoc-citeproc.git
    commit: 11308615a5b7adb76ba511c1b701fadf6186d0b1
extra-deps:
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
resolver: lts-7.5
