flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
  texmath:
    network-uri: true
packages:
- '..'
- '../pandoc-citeproc'
extra-deps:
resolver: lts-6.1
