flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '..'
- '../../pandoc-citeproc'
extra-deps:
- 'hsb2hs-0.3.1'
- 'aeson-0.11.0.0'
resolver: lts-5.2
