image: Visual Studio 2013
clone_folder: "c:\\pandoc"
environment:
  global:
    STACK_BUILD_OPTS: "--no-terminal -j1 --no-system-ghc --install-ghc --verbose --test --local-bin-path=.\\windows"
    # see #4201, https://github.com/haskell-tools/haskell-tools/issues/277
  matrix:
      #  - STACK_VERSION: "windows-i386"
      #    STACK_ROOT: "c:\\sr32"
      #    STACK_YAML: "stack.lts11.yaml"
      #    STACK: "%STACK_ROOT%\\stack.exe"
      #    STACK_FLAGS: "--flag=hslua:lua_32bits"
      #    ARCH: "x86"
      #  - STACK_VERSION: "windows-x86_64"
      #    STACK_ROOT: "c:\\sr64"
      #    STACK_YAML: "stack.lts11.yaml"
      #    STACK: "%STACK_ROOT%\\stack.exe"
      #    STACK_FLAGS: ""
      #    ARCH: "x64"
  - STACK_VERSION: "windows-i386"
    STACK_ROOT: "c:\\sr32"
    STACK_YAML: "stack.yaml"
    STACK_FLAGS: |
        --flag=hslua:lua_32bits --ghc-options --extra-prog-path=C:\Users\appveyor\AppData\Local\Programs\stack\i386-windows\msys2-20180531\mingw32\bin
    ARCH: "x86"
    CHOCO_OPTS: "--x86"
  - STACK_VERSION: "windows-x86_64"
    STACK_ROOT: "c:\\sr64"
    STACK_YAML: "stack.yaml"
    STACK_FLAGS: ""
    ARCH: "x64"
    CHOCO_OPTS: ""

skip_commits:
  files:
    - '*.md'
    - '*.txt'
    - '.travis.yml'
    - 'Makefile'
    - 'man/pandoc.1'
    - 'linux/*'
    - 'macos/*'

matrix:
  fast_finish: true

cache:
  - "%STACK_ROOT%"
  # This is where stack install ghc by default, but we don't
  # cache it because it's too large:
  # - "c:\\Users\\appveyor\\AppData\\Local\\Programs\\stack"

# Note: to reset build cache, do the following in JavaScript
# console on appveyor:
# $.ajax({ url: 'https://ci.appveyor.com/api/projects/jgm/pandoc/buildcache', type: 'DELETE'})
# We don't do a normal C build, but build in test_script via stack
build: off

install:
  - choco install wixtoolset %CHOCO_OPTS%
  - choco install haskell-stack %CHOCO_OPTS%

# before_test:

test_script:
  # The ugly echo "" hack is to avoid complaints about 0 being an invalid file
  # descriptor
  - |
      stack --version
      stack setup --stack-yaml %STACK_YAML% --no-system-ghc --install-ghc > nul
      stack path
      echo "" | stack clean
      echo "" | stack install --stack-yaml %STACK_YAML% %STACK_BUILD_OPTS% %STACK_FLAGS% pandoc pandoc-citeproc

after_test:
    # .\ in the stack commandline seems to be .\windows\ (where the stack-appveyor.yaml is)
  - cd windows
  - .\pandoc.exe -s --toc ..\MANUAL.txt -o MANUAL.html
  - .\pandoc.exe -s ..\COPYING.md -o COPYING.rtf
  - copy ..\COPYRIGHT COPYRIGHT.txt
  - 7z a "pandoc-%STACK_VERSION%.zip" pandoc.exe pandoc-citeproc.exe MANUAL.html COPYING.rtf
  - |
      set VERSION=
      for /f "tokens=1-2 delims= " %%a in ('.\pandoc.exe --version') do ( if not defined VERSION set "VERSION=%%b" )
      echo %VERSION%
      candle -arch %ARCH% -dVERSION=%VERSION% -dBINPATH=. *.wxs -out wixobj\
      light -sw1076 -ext WixUIExtension -ext WixUtilExtension -cultures:en-us -loc Pandoc-en-us.wxl -out "pandoc-%STACK_VERSION%.msi" wixobj\*.wixobj

artifacts:
  - path: 'windows\pandoc-%STACK_VERSION%.zip'
    name: exe
  - path: 'windows\pandoc-%STACK_VERSION%.msi'
    name: msi
