install:
- 'git submodule update --init'
- 'choco install haskellplatform -version 2014.2.0.0 -y'
- 'SET PATH=%PATH%;"C:\Program Files\Haskell Platform\2014.2.0.0\bin";"C:\Program Files\Haskell Platform\2014.2.0.0\lib\extralibs\bin";"C:\Program Files\Haskell Platform\2014.2.0.0\mingw\bin"'
- cabal update
- cabal install --only-dependencies --enable-tests

build_script:
- 'cabal configure --enable-tests -v2'
- 'cabal build'

test_script:
- 'cabal test'
