branches:
  only:
  - master

cache:
- "c:\\sr" # stack root, short paths == fewer problems
- "%LOCALAPPDATA%\\Programs\\stack"

build: off

before_test:
- git submodule update --init
- ps: Invoke-WebRequest "https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-x86_64-windows.zip" -OutFile stack.zip
- ps: Invoke-WebRequest "https://github.com/fpco/minghc/blob/master/bin/7z.exe?raw=true" -OutFile 7z.exe
- ps: Invoke-WebRequest "https://github.com/fpco/minghc/blob/master/bin/7z.dll?raw=true" -OutFile 7z.dll
- 7z x -oc:\\stack stack.zip
- move c:\\stack\\stack.exe stack.exe

clone_folder: "c:\\pandoc"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack --arch i386 --no-terminal --install-ghc test

