branches:
  only:
  - master

cache:
- "c:\\sr" # stack root, short paths == fewer problems
- "%LOCALAPPDATA%\\Programs\\stack"

build: off

before_test:
- git submodule update --init
- ps: Invoke-WebRequest "https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-i386-windows.zip" -OutFile stack.zip
- ps: Invoke-WebRequest "https://github.com/fpco/minghc/blob/master/bin/7z.exe?raw=true" -OutFile 7z.exe
- ps: Invoke-WebRequest "https://github.com/fpco/minghc/blob/master/bin/7z.dll?raw=true" -OutFile 7z.dll
- 7z x -oc:\\stack stack.zip
- move c:\\stack\\stack.exe stack.exe
- stack setup --arch=i386
- ps: Invoke-WebRequest "http://sourceforge.net/projects/luabinaries/files/5.1.5/Windows%20Libraries/Static/lua-5.1.5_Win64_mingw4_lib.zip/download" -OutFile lua-5.1.5.zip
- 7z x -oc:\\lua-5.1.5 lua-5.1.5.zip

clone_folder: "c:\\pandoc"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- echo "" | stack unpack hslua-0.4.1
- copy windows/hslua.cabal hslua-0.4.1/hslua.cabal
- echo "" | stack test --stack-yaml windows/stack.yaml
