install:
- cmd: git submodule update --init
- ps: >-
        choco install haskellplatform -version 2014.2.0.0 -y
        # Haskell Platfrom package doesn't update PATH for the current shell instance
        $env:Path += ";${env:ProgramFiles}\Haskell Platform\2014.2.0.0\bin"
        $env:Path += ";${env:ProgramFiles}\Haskell Platform\2014.2.0.0\lib\extralibs\bin"
        $env:Path += ";${env:ProgramFiles}\Haskell Platform\2014.2.0.0\mingw\bin"
        cabal update
        cabal install --only-dependencies --enable-tests

build_script:
- 'cabal configure --enable-tests -v2'
- 'cabal build'

test_script:
- 'cabal test'
