flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
extra-deps:
- hslua-0.5.0
- skylighting-0.3.2
- foundation-0.0.6
resolver: lts-8.8
