flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
- location:
    git: https://github.com/jgm/texmath.git
    commit: 31273683a376e97848028e4619f28ab8c03c88af
  extra-dep: true
extra-deps:
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
- skylighting-0.1.1.2
- texmath-0.9
resolver: lts-7.14
