flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
    static: false
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
# to be replaced eventually by pandoc-types-1.21:
- git: https://github.com/jgm/pandoc-types
  commit: dd50a6eaeaf63773bbf04d6ef34b86d6f92b7825
- git: https://github.com/jgm/pandoc-citeproc
  commit: 2e6fe791ec5293acc925c2ccbe79c9c10d2b7e07
- doclayout-0.3
- hslua-1.1.0
- jira-wiki-markup-1.3.0
- doctemplates-0.8.2
# downgrade HsYAML because 0.2.1.0 causes access violation
# on Windows/GHC 8.8.3
- HsYAML-0.2.0.0
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-15.11
