flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
    static: false
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
- doclayout-0.3
- doctemplates-0.8.1
- pandoc-citeproc-0.17
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-15.0
