flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
- github: jgm/pandoc-citeproc
  commit: 626b16ef8cfc71f54f5fdccf680f41e51d356f80
- haddock-library-1.6.0
- HsYAML-0.1.1.1
- network-2.7.0.2
- yaml-0.9.0
ghc-options:
   "$locals": -fhide-source-paths -XNoImplicitPrelude
resolver: lts-12.6
