flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
- location:
    git: 'https://github.com/jgm/pandoc-types'
    commit: 7b471a3d129efd8155f6cdcb2f2b58b5605df0fc
  extra-dep: true
- location: 'https://hackage.haskell.org/package/cmark-0.5.0/cmark-0.5.0.tar.gz'
  extra-dep: true
extra-deps: []
resolver: lts-3.18
