flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
# - pandoc-citeproc-0.16.2
- git: https://github.com/jgm/pandoc-citeproc
  commit: 63498fb22ae6f394f19f6d62312350b566c4aebd
- doclayout-0.1
- HsYAML-0.2.0.0
- doctemplates-0.6.1
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-14.6
