flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
extra-deps:
- hslua-0.5.0
- skylighting-0.3.3
- foundation-0.0.7
resolver: lts-8.11
