flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
# See https://github.com/haskell-foundation/foundation/pull/503
# We can go back to released foundation when this is fixed.
- location:
    git: https://github.com/jgm/foundation
    commit: '4294e39'
  subdirs:
  - foundation
  extra-dep: true
extra-deps:
- pandoc-citeproc-0.16
- ipynb-0.1
ghc-options:
   "$locals": -fhide-source-paths -XNoImplicitPrelude
resolver: lts-13.5
