flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
- location:
    git: 'https://github.com/jgm/pandoc-types'
    commit: 8aba9332f56fd23bc3c06065193abe5ace3e70b4
  extra-dep: true
- location:
    git: 'https://github.com/jgm/texmath'
    commit: 6aad84f3d833604cf6bbaafdec68bf047e3b4c4d
  extra-dep: true
extra-deps: []
resolver: lts-3.16
