flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
- pandoc-citeproc-0.12.2.5
- hslua-0.9.5
- skylighting-0.5.1
- tasty-1.0
resolver: lts-10.3
