flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
- location:
    git: https://github.com/jgm/texmath.git
    commit: 716614e6854a0a25f630896b247d9ff9b55e1995
extra-deps:
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
resolver: lts-7.9
