flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
- 'https://hackage.haskell.org/package/pandoc-types-1.12.4.6/pandoc-types-1.12.4.6.tar.gz'
extra-deps: []
resolver: lts-3.4
