flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '.'
extra-deps:
- pandoc-citeproc-0.14.3.1
- haddock-library-1.6.0
- HsYAML-0.1.1.1
- network-2.7.0.2
ghc-options:
   "$locals": -fhide-source-paths -XNoImplicitPrelude
resolver: lts-12.0
