flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
extra-deps:
- doctemplates-0.1.0.2
- texmath-0.8.6.6
- pandoc-types-1.17.0.1
resolver: lts-7.2
