flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
ghc-options:
  pandoc-citeproc:  '-pgmP cpphs -optP--cpp'
  highlighting-kate: '-pgmP cpphs -optP--cpp'
packages:
- '..'
extra-deps:
- pandoc-citeproc-0.10.1.2
- doctemplates-0.1.0.2
- texmath-0.8.6.6
- pandoc-types-1.17
resolver: lts-7.2
