flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
ghc-options:
  pandoc-citeproc:  '-pgmP cpphs -optP--cpp'
  highlighting-kate: '-pgmP cpphs -optP--cpp'
packages:
- '..'
- 'https://hackage.haskell.org/package/pandoc-citeproc-0.9/pandoc-citeproc-0.9.tar.gz'
extra-deps:
resolver: lts-5.2
