flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
ghc-options:
  pandoc-citeproc:  '-pgmP cpphs -optP--cpp'
  highlighting-kate: '-pgmP cpphs -optP--cpp'
packages:
- '..'
- location:
    git: https://github.com/jgm/pandoc-citeproc.git
    commit: 1fb0ac09952ea69dac528652165d9d65313b77d4
extra-deps:
- doctemplates-0.1.0.2
- pandoc-types-1.17.0.4
resolver: lts-7.5
