flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '..'
extra-deps:
- 'cmark-0.5.0'
- 'pandoc-citeproc-0.9'
- 'pandoc-types-1.16'
resolver: lts-3.20
