name: Haskell CI

on: [push]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install recent cabal/ghc
      run: |
          sudo add-apt-repository ppa:hvr/ghc
          sudo apt-get update
          sudo apt-get install ghc-8.6.4 cabal-install-2.4
    - name: Install dependencies
      run: |
          export PATH=/opt/cabal/bin:/opt/ghc/bin:$PATH
          cabal v2-update
          cabal v2-build --dependencies-only --enable-tests
    - name: Build
      run: |
          export PATH=/opt/cabal/bin:/opt/ghc/bin:$PATH
          cabal v2-build --enable-tests
    - name: Run tests
      run: |
          export PATH=/opt/cabal/bin:/opt/ghc/bin:$PATH
          cabal v2-test

  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install stack
      shell: cmd
      run: |
          choco install haskell-stack
    - name: Build and test
      shell: cmd
      run: |
          stack update
          stack test
